## Intro to Numpy

In [1]:
import numpy as np

## Numpy Data Types and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.ndim

1

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a DataFrame from a Numpy array
import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [22]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [23]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [24]:
a1_df = pd.DataFrame(a1)
a1_df

0
0  1
1  2
2  3

## So machine learning finding different patterns in Numpy Array

In [25]:
# Create a Numpy array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [26]:
# Create a Numpy array of ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
ones_int_type = np.ones((2, 3), dtype=int)
ones_int_type

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
# Create a Numpy array of range
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [31]:
random_array

array([[5, 9, 4, 4, 0],
       [1, 5, 5, 7, 2],
       [2, 2, 4, 4, 8]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.51063949, 0.27629548, 0.82093517],
       [0.13619236, 0.90789623, 0.98611203],
       [0.26352167, 0.68428262, 0.56016498],
       [0.71147787, 0.33588189, 0.19683668],
       [0.2423228 , 0.52541664, 0.02866628]])

In [48]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ]])

In [50]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [51]:
random_array_4.size

15

In [52]:
random_array_4.shape

(5, 3)

In [53]:
np.random.seed(7)

In [54]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [55]:
random_array_5.shape

(5, 3)

In [56]:
random_array_5.size

15

In [59]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])