## Intro to Numpy

In [1]:
import numpy as np

## Numpy Data Types and Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])

In [6]:
a2
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [10]:
a1.shape

(3,)

In [11]:
a2.shape

(2, 3)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
a2.ndim

2

In [15]:
a3.ndim

3

In [16]:
a1.ndim

1

In [17]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [18]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [19]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [20]:
# Create a DataFrame from a Numpy array
import pandas as pd

In [21]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [22]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [23]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [24]:
a1_df = pd.DataFrame(a1)
a1_df

0
0  1
1  2
2  3

## So machine learning finding different patterns in Numpy Array

In [25]:
# Create a Numpy array
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [26]:
# Create a Numpy array of ones
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
ones_int_type = np.ones((2, 3), dtype=int)
ones_int_type

array([[1, 1, 1],
       [1, 1, 1]])

In [29]:
# Create a Numpy array of range
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [31]:
random_array

array([[5, 9, 4, 4, 0],
       [1, 5, 5, 7, 2],
       [2, 2, 4, 4, 8]])

In [32]:
random_array.size

15

In [33]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.51063949, 0.27629548, 0.82093517],
       [0.13619236, 0.90789623, 0.98611203],
       [0.26352167, 0.68428262, 0.56016498],
       [0.71147787, 0.33588189, 0.19683668],
       [0.2423228 , 0.52541664, 0.02866628]])

In [48]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395],
       [0.0187898 , 0.6176355 , 0.61209572],
       [0.616934  , 0.94374808, 0.6818203 ]])

In [50]:
# Pseudo-random numbers
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [51]:
random_array_4.size

15

In [52]:
random_array_4.shape

(5, 3)

In [53]:
np.random.seed(7)

In [54]:
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [55]:
random_array_5.shape

(5, 3)

In [56]:
random_array_5.size

15

In [59]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [60]:
np.unique(random_array_5)

array([0.06593635, 0.07205113, 0.07630829, 0.26843898, 0.2881456 ,
       0.38094113, 0.43840923, 0.4998825 , 0.50112046, 0.53849587,
       0.67923   , 0.72346518, 0.77991879, 0.80373904, 0.97798951])

In [61]:
unique_elements, counts = np.unique(random_array_5, return_counts=True)

In [62]:
unique_elements

array([0.06593635, 0.07205113, 0.07630829, 0.26843898, 0.2881456 ,
       0.38094113, 0.43840923, 0.4998825 , 0.50112046, 0.53849587,
       0.67923   , 0.72346518, 0.77991879, 0.80373904, 0.97798951])

In [63]:
duplicates = unique_elements[counts > 1]
duplicates

array([], dtype=float64)

## Viewing arrays and matrices

In [64]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [65]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [67]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
a3[0][0]

array([1, 2, 3])

In [69]:
a3[0][0][0]

1

In [70]:
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [71]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [72]:
a3.shape

(2, 3, 3)

In [73]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

## Get the first 4 numbers of the inner most arrays

In [74]:
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [76]:
a4[0][0][0]

array([3, 5, 8, 8, 7])

In [77]:
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

In [78]:
a4[:, :, :, :4].shape

(2, 3, 4, 4)

## Manipulating and comparing arrays

### Arithmetic

In [80]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [81]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [82]:
ones = np.ones(3)

In [83]:
ones + a1

array([2., 3., 4.])

In [84]:
a1 - ones

array([0., 1., 2.])

In [85]:
a1 * ones

array([1., 2., 3.])

In [86]:
a1.shape

(3,)

In [87]:
a2.shape

(2, 3)

In [88]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [89]:
a3.shape

(2, 3, 3)

In [93]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [94]:
reshaped_a2 = a2.reshape(2, 3, 1)

In [95]:
reshaped_a2 * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [96]:
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [97]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [98]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [99]:
np.add(a1, ones)

array([2., 3., 4.])

### Aggregation

In [101]:
np.sum(a1)

6

In [102]:
massive_array = np.random.random(100000)

In [103]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [104]:
%timeit sum(massive_array) # Python's sum()

12.3 ms ± 585 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [105]:
%timeit np.sum(massive_array) # Numpy's sum()

78.6 µs ± 14.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


## magic function start with %

In [106]:
np.mean(a2)

3.6333333333333333

In [107]:
np.max(a2)

6.5

In [108]:
np.min(a2)

1.0

# Standard deviation = a measure of how spread out a group of numbers is from the mean

In [111]:
np.std(a2)

1.8226964152656422