# Dot product excerise

In [6]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(0)

In [4]:
sales_amount = np.random.randint(20, size=(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [11]:
columns = ["Almond butter", "Peanut butter", "Cashew butter"]

In [12]:
# Create weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amount,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                            columns=columns)

In [13]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon               12             15              0
Tues               3              3              7
Wed                9             19             18
Thurs              4              6             12
Fri                1              6              7

In [14]:
# Create prices array
prices = np.array([10, 8, 12])
prices

array([10,  8, 12])

In [15]:
pd_prices = pd.DataFrame(prices.reshape(1,3),
                         index=["Price"],
                         columns=columns)
pd_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [16]:
prices.shape

(3,)

In [17]:
prices.reshape(1,3).shape

(1, 3)

In [18]:
pd_prices, weekly_sales

(       Almond butter  Peanut butter  Cashew butter
 Price             10              8             12,
        Almond butter  Peanut butter  Cashew butter
 Mon               12             15              0
 Tues               3              3              7
 Wed                9             19             18
 Thurs              4              6             12
 Fri                1              6              7)

In [19]:
total = prices.dot(sales_amount.T)
total

array([240, 138, 458, 232, 142])

In [20]:
weekly_sales["Total"] = total
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total
Mon               12             15              0    240
Tues               3              3              7    138
Wed                9             19             18    458
Thurs              4              6             12    232
Fri                1              6              7    142